language: python
cache:
  pip: true

python:
- "3.4"
- "3.5"
- "3.6"

matrix:
  include:
  - python: "3.7"
    dist: xenial
    sudo: true
  - python: "3.8"
    dist: xenial
    sudo: true

install:
- pip install nose coveralls pyOpenSSL
- pip install .
script:
- nosetests --with-cover --cover-package aiosasl tests
after_success:
- if [[ "$TRAVIS_PYTHON_VERSION" == '3.6' ]]; then coveralls; fi
